modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cobblemonshinydays"
version = "${version}"
displayName = "Cobblemon Shiny Days"
authors = "Shadymitsu & ChatGPT"
description = "Increase shiny rates on certain days!"
logoFile = "/ShinyDaysIcon.png"

[[dependencies.cobblemon_neoforge_mdk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_neoforge_mdk]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_neoforge_mdk]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,1.7.0)"
ordering = "AFTER"
side = "BOTH"
